import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WebHeader from "./components/webheader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Parit Weather App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	
	
	return (
		<html lang="en">
			<body className="bg-gradient-to-r from-violet-600 to-indigo-600">
				{children}
			</body>
		</html>
	);
}
